exclusions:
- code: '000547'
  dates:
  - '2023-07-13'
- code: '000885'
  dates:
  - '2025-07-04'
- code: '000995'
  dates:
  - '2023-07-07'
  - '2023-07-13'
- code: '001465'
  dates:
  - '2024-04-17'
- code: '001529'
  dates:
  - '2022-07-06'
  - '2022-07-07'
  - '2022-07-08'
  - '2022-07-11'
  - '2022-07-12'
  - '2022-07-13'
  - '2022-07-14'
- code: '001745'
  dates:
  - '2023-07-06'
  - '2023-07-07'
  - '2023-07-10'
  - '2023-07-13'
  - '2023-07-14'
- code: '004565'
  dates:
  - '2023-07-06'
  - '2023-07-07'
  - '2023-07-13'
- code: '005450'
  dates:
  - '2020-06-19'
  - '2020-06-23'
- code: '007630'
  dates:
  - '2022-02-11'
  - '2022-02-15'
- code: '008800'
  dates:
  - '2021-05-27'
  - '2021-05-28'
- code: '009275'
  dates:
  - '2022-07-08'
  - '2022-07-13'
  - '2022-07-14'
- code: '009415'
  dates:
  - '2024-07-12'
- code: '010145'
  dates:
  - '2023-07-06'
  - '2023-07-07'
  - '2023-07-10'
  - '2023-07-13'
  - '2023-07-14'
- code: '012170'
  dates:
  - '2025-03-06'
- code: '012600'
  dates:
  - '2025-05-16'
- code: '014200'
  dates:
  - '2025-11-17'
  - '2025-11-18'
  - '2025-11-25'
- code: '015540'
  dates:
  - '2023-10-27'
  - '2023-10-30'
  - '2023-11-01'
  - '2023-11-02'
- code: '016385'
  dates:
  - '2022-07-08'
  - '2022-07-13'
  - '2022-07-14'
- code: '019570'
  dates:
  - '2023-05-03'
- code: '019590'
  dates:
  - '2025-08-28'
- code: '021045'
  dates:
  - '2024-09-25'
- code: '023460'
  dates:
  - '2025-07-03'
  - '2025-07-10'
  - '2025-07-11'
- code: '024810'
  dates:
  - '2025-09-01'
  - '2025-09-03'
  - '2025-09-04'
  - '2025-09-08'
  - '2025-09-09'
- code: '028040'
  dates:
  - '2021-04-02'
  - '2021-04-12'
- code: '029480'
  dates:
  - '2023-03-22'
- code: '030270'
  dates:
  - '2020-05-12'
  - '2020-05-18'
  - '2020-05-19'
  - '2020-05-20'
- code: '030790'
  dates:
  - '2024-04-30'
  - '2024-05-10'
- code: '033110'
  dates:
  - '2021-09-28'
  - '2021-10-05'
  - '2021-10-06'
  - '2021-10-07'
- code: '033430'
  dates:
  - '2021-08-24'
- code: '033600'
  dates:
  - '2021-08-02'
  - '2021-08-03'
  - '2021-08-05'
  - '2021-08-06'
  - '2021-08-09'
- code: '033790'
  dates:
  - '2023-03-30'
- code: '036260'
  dates:
  - '2021-02-02'
  - '2021-02-03'
  - '2021-02-05'
  - '2021-02-08'
  - '2021-02-10'
- code: '038160'
  dates:
  - '2021-08-20'
- code: '038340'
  dates:
  - '2025-03-19'
  - '2025-03-21'
  - '2025-03-24'
  - '2025-03-27'
- code: '039230'
  dates:
  - '2021-09-24'
  - '2021-09-27'
  - '2021-10-05'
- code: '039670'
  dates:
  - '2022-04-11'
  - '2022-04-14'
  - '2022-04-15'
  - '2022-04-18'
  - '2022-04-19'
- code: '044060'
  dates:
  - '2025-08-11'
- code: '045890'
  dates:
  - '2021-12-09'
  - '2021-12-13'
  - '2021-12-14'
  - '2021-12-17'
- code: '050090'
  dates:
  - '2023-05-08'
- code: '050320'
  dates:
  - '2022-05-20'
  - '2022-05-25'
  - '2022-05-26'
  - '2022-05-27'
- code: '050540'
  dates:
  - '2022-01-24'
  - '2023-04-27'
  - '2023-04-28'
  - '2023-05-02'
  - '2023-05-04'
- code: '052190'
  dates:
  - '2022-05-18'
  - '2022-05-19'
  - '2022-05-20'
  - '2022-05-24'
  - '2022-05-25'
  - '2022-05-26'
- code: '053110'
  dates:
  - '2022-08-29'
  - '2022-08-30'
  - '2022-09-01'
  - '2022-09-02'
  - '2022-09-05'
  - '2022-09-06'
- code: '053590'
  dates:
  - '2024-09-24'
  - '2024-10-02'
  - '2024-10-04'
- code: '053660'
  dates:
  - '2022-04-15'
  - '2022-04-22'
  - '2022-04-25'
- code: '054340'
  dates:
  - '2020-05-12'
  - '2020-05-13'
  - '2020-05-14'
  - '2020-05-18'
  - '2020-05-19'
  - '2020-05-20'
- code: '054630'
  dates:
  - '2025-12-18'
  - '2025-12-23'
- code: '056000'
  dates:
  - '2023-03-21'
  - '2023-03-28'
  - '2023-03-29'
- code: '058420'
  dates:
  - '2023-04-05'
  - '2023-04-12'
  - '2023-04-13'
- code: '058450'
  dates:
  - '2023-12-12'
- code: '058970'
  dates:
  - '2021-08-13'
- code: '060300'
  dates:
  - '2022-10-26'
  - '2022-10-31'
- code: '062860'
  dates:
  - '2024-11-12'
- code: '065560'
  dates:
  - '2024-07-18'
  - '2024-07-23'
- code: '065620'
  dates:
  - '2021-07-29'
  - '2021-08-02'
  - '2021-08-05'
  - '2021-08-06'
- code: '065940'
  dates:
  - '2020-07-22'
  - '2020-07-28'
  - '2020-07-29'
  - '2020-07-30'
- code: '066110'
  dates:
  - '2022-03-28'
  - '2022-03-30'
- code: '069110'
  dates:
  - '2023-10-11'
- code: '071460'
  dates:
  - '2025-06-09'
  - '2025-06-10'
  - '2025-06-16'
  - '2025-06-17'
- code: '072520'
  dates:
  - '2025-06-09'
  - '2025-06-10'
  - '2025-06-11'
  - '2025-06-12'
  - '2025-06-16'
  - '2025-06-17'
- code: '073070'
  dates:
  - '2021-05-26'
  - '2021-05-28'
- code: '078650'
  dates:
  - '2023-07-12'
  - '2023-07-17'
  - '2023-07-18'
  - '2023-07-19'
  - '2023-07-20'
- code: '078860'
  dates:
  - '2023-12-27'
- code: '078940'
  dates:
  - '2025-02-10'
  - '2025-02-11'
  - '2025-02-12'
- code: '079970'
  dates:
  - '2024-08-21'
- code: '080440'
  dates:
  - '2021-09-02'
  - '2021-09-06'
  - '2021-09-07'
  - '2021-09-09'
  - '2021-09-10'
- code: '086250'
  dates:
  - '2021-08-20'
  - '2021-08-26'
- code: '087730'
  dates:
  - '2021-09-28'
  - '2021-09-29'
  - '2021-10-01'
  - '2021-10-05'
  - '2021-10-06'
  - '2021-10-07'
- code: '089530'
  dates:
  - '2024-08-28'
- code: '090740'
  dates:
  - '2022-10-05'
  - '2022-10-13'
- code: '091090'
  dates:
  - '2025-10-16'
  - '2025-10-23'
- code: '093230'
  dates:
  - '2025-09-02'
  - '2025-09-03'
  - '2025-09-09'
  - '2025-09-10'
- code: '094190'
  dates:
  - '2020-05-13'
  - '2020-05-14'
  - '2020-05-15'
  - '2020-05-18'
  - '2020-05-21'
- code: '096040'
  dates:
  - '2025-09-01'
  - '2025-09-03'
  - '2025-09-08'
  - '2025-09-09'
- code: '096640'
  dates:
  - '2023-07-06'
  - '2023-07-14'
- code: '101000'
  dates:
  - '2023-04-21'
- code: '101680'
  dates:
  - '2023-03-28'
- code: '102210'
  dates:
  - '2021-04-08'
  - '2021-04-12'
  - '2021-04-16'
- code: '102280'
  dates:
  - '2025-11-19'
  - '2025-11-20'
  - '2025-11-27'
- code: '103130'
  dates:
  - '2020-05-21'
  - '2020-05-22'
  - '2020-05-25'
  - '2020-05-28'
  - '2020-05-29'
- code: '103230'
  dates:
  - '2023-03-28'
- code: '109960'
  dates:
  - '2023-04-07'
- code: '110790'
  dates:
  - '2023-10-20'
- code: '111820'
  dates:
  - '2021-09-16'
  - '2021-09-27'
  - '2021-09-28'
  - '2021-09-29'
- code: '112240'
  dates:
  - '2020-06-19'
  - '2020-06-22'
- code: '114120'
  dates:
  - '2024-02-02'
  - '2024-02-05'
  - '2024-02-06'
  - '2024-02-07'
  - '2024-02-13'
  - '2024-02-14'
- code: '114570'
  dates:
  - '2022-02-14'
  - '2022-02-18'
- code: '121890'
  dates:
  - '2023-10-23'
- code: '122800'
  dates:
  - '2020-02-03'
  - '2020-02-06'
  - '2020-02-10'
  - '2020-02-11'
- code: '123260'
  dates:
  - '2020-04-01'
  - '2020-04-02'
  - '2020-04-03'
  - '2020-04-07'
  - '2020-04-08'
  - '2020-04-09'
- code: '126870'
  dates:
  - '2022-10-17'
- code: '127160'
  dates:
  - '2022-09-08'
  - '2022-09-19'
  - '2022-09-20'
  - '2022-09-21'
- code: '134780'
  dates:
  - '2020-06-23'
  - '2020-06-24'
  - '2020-07-01'
- code: '136510'
  dates:
  - '2024-07-16'
  - '2024-07-18'
- code: '138690'
  dates:
  - '2023-11-27'
  - '2023-11-28'
- code: '139050'
  dates:
  - '2023-06-28'
- code: '141020'
  dates:
  - '2023-12-20'
  - '2023-12-21'
  - '2023-12-22'
  - '2024-01-02'
- code: '141070'
  dates:
  - '2021-09-07'
  - '2021-09-09'
  - '2021-09-10'
  - '2021-09-13'
  - '2021-09-15'
- code: '148140'
  dates:
  - '2024-05-28'
  - '2024-05-31'
  - '2024-06-03'
  - '2024-06-04'
- code: '148780'
  dates:
  - '2022-06-20'
- code: '149940'
  dates:
  - '2020-07-08'
  - '2020-07-09'
- code: '151910'
  dates:
  - '2025-11-17'
  - '2025-11-25'
- code: '158310'
  dates:
  - '2022-10-31'
  - '2022-11-02'
  - '2022-11-08'
- code: '159910'
  dates:
  - '2023-12-27'
- code: '160600'
  dates:
  - '2025-02-05'
  - '2025-02-11'
- code: '161570'
  dates:
  - '2024-06-05'
  - '2024-06-14'
- code: '176440'
  dates:
  - '2022-06-16'
  - '2022-06-20'
  - '2022-06-23'
- code: '181340'
  dates:
  - '2024-07-01'
  - '2024-07-02'
- code: '182690'
  dates:
  - '2022-08-19'
  - '2022-10-07'
  - '2022-10-12'
  - '2022-10-13'
  - '2022-10-14'
- code: '195440'
  dates:
  - '2021-06-01'
  - '2021-06-02'
  - '2021-06-03'
  - '2021-06-09'
- code: '197210'
  dates:
  - '2020-05-04'
  - '2020-05-07'
  - '2020-05-11'
  - '2020-05-12'
  - '2020-05-13'
- code: '204990'
  dates:
  - '2020-07-31'
  - '2020-08-03'
  - '2020-08-07'
- code: '214310'
  dates:
  - '2024-12-12'
  - '2024-12-13'
  - '2024-12-20'
- code: '214870'
  dates:
  - '2025-03-20'
  - '2025-03-27'
- code: '221610'
  dates:
  - '2021-12-24'
  - '2021-12-27'
  - '2021-12-28'
  - '2021-12-29'
  - '2022-01-04'
- code: '225220'
  dates:
  - '2020-07-24'
- code: '226350'
  dates:
  - '2021-06-02'
  - '2021-06-03'
  - '2021-06-04'
  - '2021-06-07'
- code: '226440'
  dates:
  - '2025-06-10'
  - '2025-06-18'
- code: '232680'
  dates:
  - '2021-06-17'
- code: '239890'
  dates:
  - '2021-02-16'
- code: '263540'
  dates:
  - '2024-10-28'
  - '2024-11-05'
- code: '268600'
  dates:
  - '2025-02-25'
  - '2025-02-26'
  - '2025-03-04'
  - '2025-03-05'
- code: '270660'
  dates:
  - '2021-02-17'
  - '2021-07-28'
- code: '290380'
  dates:
  - '2025-08-11'
  - '2025-08-12'
- code: '299910'
  dates:
  - '2025-02-05'
  - '2025-02-06'
  - '2025-02-10'
- code: '323230'
  dates:
  - '2025-06-10'
  - '2025-06-11'
  - '2025-06-13'
  - '2025-06-16'
  - '2025-06-17'
  - '2025-06-18'
- code: 33637L
  dates:
  - '2024-01-08'
- code: '366330'
  dates:
  - '2023-06-02'
- code: '367360'
  dates:
  - '2023-08-18'
- code: '367480'
  dates:
  - '2023-04-14'
- code: '393210'
  dates:
  - '2023-04-27'
- code: '400560'
  dates:
  - '2023-05-08'
- code: '404950'
  dates:
  - '2023-09-22'
- code: '405350'
  dates:
  - '2023-07-14'
- code: '409570'
  dates:
  - '2023-04-28'
- code: '425040'
  dates:
  - '2023-12-28'
  - '2024-01-02'
- code: '900040'
  dates:
  - '2020-05-13'
  - '2020-05-14'
  - '2020-05-21'
- code: '900080'
  dates:
  - '2021-06-03'
- code: '900280'
  dates:
  - '2024-12-26'
  - '2024-12-27'
  - '2025-01-06'
  - '2025-01-07'
- code: '900300'
  dates:
  - '2024-12-04'
