# config/kis_keys.yaml
app_key: "PSmyIiU4804gAGSTt8sGg5Pg5YEL9ZbzXWqX"
app_secret: "mQ90yspl+jDWpYJRvR/o0K86EtJRSpw4XPiPBBi6781r8uc5pyvXwJoNctxoqzebbdm5aQq2NWc/oJhxw9ktYroW/17hpINnqUTi7WSswpOZAYPcpDQEnGVPBGWdJmgoUhrxPF99JsxvyveszIMFD+0PepPoOjo5ky/ZxV2DbTRDYyV3Dtg="